services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - ./root.crt:/root/.postgresql/root.crt # Mount certificate
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - app
    restart: unless-stopped
