"""create revoked_tokens

Revision ID: cdd6aabc453c
Revises: d5cdcec7960c
Create Date: 2025-01-28 00:32:02.594225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdd6aabc453c'
down_revision: Union[str, None] = 'd5cdcec7960c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('removed_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti')
    )
    op.create_index(op.f('ix_removed_tokens_id'), 'removed_tokens', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_removed_tokens_id'), table_name='removed_tokens')
    op.drop_table('removed_tokens')
    # ### end Alembic commands ###
